<a href="https://colab.research.google.com/github/CHARANRAJ45/deep_learning_____pytorch/blob/main/next_word_lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [42]:
df = pd.read_csv('qoute_dataset.csv')

In [43]:
df.shape

(3038, 2)

In [44]:
qouts = df['quote']

In [45]:
qouts.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [46]:
qouts = qouts.str.lower()

In [47]:
import string
translator = str.maketrans('','',string.punctuation)
qouts=qouts.apply(lambda x:x.translate(translator) )

In [48]:
qouts.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [49]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [50]:
vocb_size=9000
tokinzer = Tokenizer(num_words=vocb_size)
tokinzer.fit_on_texts(qouts)

In [51]:
word_indx = tokinzer.word_index
print(len(word_indx))
list(word_indx.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [52]:
sequence = tokinzer.texts_to_sequences(qouts)

In [53]:
for i in range(3):
  print(qouts[i])
  print("/n")
  print(sequence[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
/n
[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
“it is our choices harry that show what we truly are far more than our abilities”
/n
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
/n
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [54]:
x=[]
y=[]

for seq in sequence:
  for i in range(len(seq)):
    input_seq=seq[:i]
    out_seq = seq[i]
    x.append(input_seq)
    y.append(out_seq)

In [55]:
len(x)

88309

In [56]:
maxlen = max(len(n) for n in x)

In [57]:
maxlen

745

In [58]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_padded = pad_sequences(x,maxlen=maxlen,padding='pre')

In [59]:
y=np.array(y)

In [60]:
x_padded.shape

(88309, 745)

In [61]:
from tensorflow.keras.utils import to_categorical
y_cat = to_categorical(y,num_classes=vocb_size)

In [62]:
y_cat.shape

(88309, 9000)

In [63]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

In [64]:
embeddings=50
rnn_uniits=128

In [65]:
rnn_model = Sequential([
    Embedding(vocb_size,embeddings,input_length=maxlen),
    SimpleRNN(rnn_uniits),
    Dense(vocb_size,activation='softmax')


])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [66]:
rnn_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [67]:
rnn_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [68]:
lstm_model = Sequential([
    Embedding(vocb_size,embeddings,input_length=maxlen),
    LSTM(rnn_uniits),
    Dense(vocb_size,activation='softmax')
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [69]:
lstm_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [70]:
lstm_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model.fit(x_padded,y_cat,epochs=20,verbose=0)